name: Build
on:
  push:
    tags:
      - 'v*'
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Install system packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: ^libxcb.*-dev libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
      - uses: lukka/get-cmake@latest
      - name: Install dependencies # saves / restores cache to avoid rebuilding dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 215a2535590f1f63788ac9bd2ed58ad15e6afdff
      - name: Run CMake and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "linux-debug"
          buildPreset: "linux-debug"

  build-macos:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
    steps:
      - uses: actions/checkout@v4
      - name: Install system packages
        uses: ConorMacBride/install-package@v1
        with:
          brew: pkg-config
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: lukka/get-cmake@latest
      - name: Install dependencies # saves / restores cache to avoid rebuilding dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 215a2535590f1f63788ac9bd2ed58ad15e6afdff
      - name: Run CMake and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "macos-debug"
          buildPreset: "macos-debug"

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Install dependencies # saves / restores cache to avoid rebuilding dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 215a2535590f1f63788ac9bd2ed58ad15e6afdff
      - name: Run CMake and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "windows-release"
          buildPreset: "windows-release"
          packagePreset: "windows-release"
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: "out/windows-release/dist/*.zip"
          fail_on_unmatched_files: true
          generate_release_notes: true
